namespace: temporal-system

replicaCount: 1

image:
  repository: controller
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: controller-manager

podAnnotations:
  # Additional pod annotations can be added here
  ad.datadoghq.com/manager.checks: |
    {
      "openmetrics": {
        "init_config": {},
        "instances": [
          {
            "openmetrics_endpoint": "http://%%host%%:%%port%% ",
            "namespace": "temporal_worker_controller",
            "metrics": [".*"]
          }
        ]
      }
    }

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

terminationGracePeriodSeconds: 10 