apiVersion: temporal.io/v1alpha1
kind: TemporalWorker
metadata:
  name: helloworld
  labels:
    app.kubernetes.io/name: hello-world-worker
    app.kubernetes.io/instance: demo
spec:
  # Configuration for connecting to Temporal
  workerOptions:
    connection: dev-server
    temporalNamespace: "replay-2025.ktasd"
  # How to cut over new workflow executions to the latest worker version
  cutover:
    strategy: AllAtOnce
    gate:
      workflowType: "HelloWorld"
  # Desired number of worker replicas
  replicas: 1
  # Desired specification for worker pods
  template:
    metadata:
      annotations:
        force-new-version: ""
        ad.datadoghq.com/main.checks: |
          {
            "openmetrics": {
              "init_config": {},
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:9090/metrics",
                  "metrics": [".*"]
                }
              ]
            }
          }
    spec:
      containers:
        - name: main
          image: helloworld
          readinessProbe:
            httpGet:
              port: 8080
          env:
          - name: TEMPORAL_TASK_QUEUE
            value: "hello_world"
---
apiVersion: temporal.io/v1alpha1
kind: TemporalConnection
metadata:
  name: dev-server
spec:
  hostPort: "replay-2025.ktasd.tmprl.cloud:7233"
  mutualTLSSecret: temporal-cloud-mtls
