apiVersion: temporal.io/v1alpha1
kind: TemporalWorkerDeployment
metadata:
  name: helloworld
  namespace: staging
  labels:
    app: helloworld
spec:
  # Configuration for connecting to Temporal
  workerOptions:
    connection: cloud-demo
    temporalNamespace: worker-controller-demo.a2dd6

  # How to roll out new workflow executions to the latest worker version
  rollout:
    strategy: Progressive
    steps:
      - rampPercentage: 1
        pauseDuration: 30s
      - rampPercentage: 50
        pauseDuration: 1m
    gate:
      workflowType: HelloWorld
  sunset:
    scaledownDelay: 30s
    deleteDelay: 1m
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPORAL_TASK_QUEUE
              value: hello_world
---
apiVersion: temporal.io/v1alpha1
kind: TemporalConnection
metadata:
  name: cloud-demo
spec:
  hostPort: worker-controller-demo.a2dd6.tmprl.cloud:7233
  mutualTLSSecret: temporal-cloud-mtls
