apiVersion: temporal.io/v1alpha1
kind: TemporalWorkerDeployment
metadata:
  name: worker
  namespace: staging
  labels:
    app: worker
spec:
  # Configuration for connecting to Temporal
  workerOptions:
    connection: cloud-demo
    temporalNamespace: "{{ .Values.temporal.namespace }}"

  # How to roll out new workflow executions to the latest worker version
  rollout:
    strategy: Progressive
    steps:
      - rampPercentage: 1
        pauseDuration: 30s
      - rampPercentage: 50
        pauseDuration: 1m
    gate:
      workflowType: "HelloWorld"
  sunset:
    scaledownDelay: 30s
    deleteDelay: 1m
  replicas: 4
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPORAL_TASK_QUEUE
              value: "{{ .Values.temporal.taskQueue }}"
---
apiVersion: temporal.io/v1alpha1
kind: TemporalConnection
metadata:
  name: cloud-demo
spec:
  hostPort: "{{ .Values.temporal.namespace }}.tmprl.cloud:7233"
  mutualTLSSecret: "{{ .Values.temporal.mTLSSecret }}"
