apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: staging
  labels:
    app: worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPORAL_TASK_QUEUE
              value: "{{ .Values.temporal.taskQueue }}"
            - name: TEMPORAL_NAMESPACE
              value: "{{ .Values.temporal.namespace }}"
            - name: TEMPORAL_HOST_PORT
              value: "{{ .Values.temporal.namespace }}.tmprl.cloud:7233"
            - name: TEMPORAL_TLS_KEY_PATH
              value: /etc/temporal/tls/tls.key
            - name: TEMPORAL_TLS_CERT_PATH
              value: /etc/temporal/tls/tls.crt
          volumeMounts:
            - mountPath: /etc/temporal/tls
              name: temporal-tls
              readOnly: true
      volumes:
        - name: temporal-tls
          secret:
            secretName: "{{ .Values.temporal.mTLSSecret }}"
            defaultMode: 420
