apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "temporal-worker-controller.labels" . | nindent 4 }}
    control-plane: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: worker-controller
    app.kubernetes.io/part-of: worker-controller
    app.kubernetes.io/managed-by: {{ .Release.Service }} 